---
- name: Run frontend container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ frontend_port }}"
    networks:
      - name: "{{ docker_network }}"
    env: 
      REACT_APP_BACKEND_URL: "http://{{ backend_ip }}:{{ backend_port }}"
  tags:
    - frontend
  become: true