version: '3'
services:

  mongo:
    image: mongo:4.4  # Use official lightweight MongoDB image
    container_name: mongo-app
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: yolo-backend-v1  
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo-app:27017/products
    depends_on:
      - mongo
    networks:
      - app-net

  frontend:
    build: ./client
    container_name: yolo-frontend-v1
    ports:
      - "3000:80"  # Nginx or other static file server exposed port
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
