version: '3'
services:
  backend:
    build: ./backend
    container_name: yolo-backend-v1  
    ports:
      - "5000:5000"
    environment:
      - USE_MOCK_DB=true  # Use mock DB in production
    networks:
      - app-net

  frontend:
    build: ./client
    container_name: yolo-frontend-v1
    ports:
      - "3000:80"  # Nginx or other static file server exposed port
    depends_on:
      - backend  # Frontend depends on the backend
    networks:
      - app-net

volumes:
  mongo-data:  # Can be removed, since we're not using MongoDB anymore

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
