version: '3.8'
services:
  mongo:
    image: papetua/mongo:v2.0.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net
    command: mongod --noauth --bind_ip_all
    user: root

  backend:
    image: papetua/yolo_backend:v2.0.0
    container_name: yolo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - app-net

  frontend:
    build: ./client
    image: papetua/yolo_frontend:v2.0.0
    container_name: yolo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16