services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: yolo-backend-v1  
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo
    networks:
      - app-net

  frontend:
    build: ./client
    container_name: yolo-frontend-v1  # 
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
