services:
  mongo:
    image: papetua/mongo:v2.0.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net
    command: mongod --noauth --bind_ip_all
    user: root

  backend:
    image: papetua/yolo_backend:v3.0.0
    build:
      context: ./backend
    container_name: yolo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
      - FRONTEND_URL=http://yolo-frontend:3000
    depends_on:
      - mongo
    networks:
      - app-net

  frontend:
    image: papetua/yolo_frontend:v3.0.0
    build:
      context: ./client
    container_name: yolo-frontend
    environment:
      - REACT_APP_API_URL=http://yolo-backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16