---
- name: Setup E-coomerce Application
  hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml


  roles:
    - docker 
    - setup-mongodb
    - backend-deployment
    - frontend-deployment
       
    
    