---
- name: Setup E-coomerce Application
  hosts: all
  become: yes

  vars_files:
    - group_vars/all.yml

    
  roles: 
    - frontend-deployment
    - setup-mongodb   
    - backend-deployment
    