---
- name: Run MongoDB Container
  docker_container:
    name: mongo
    image: mongo
    state: started
    restart_policy: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
    networks:
      - name: app-net
  tags:
    - database
    - backend