---
- name: Create Docker network
  docker_network:
    name: app-net
    state: present

- name: Create MongoDB volume
  docker_volume:
    name: mongo_data
    state: present

- name: Run MongoDB Container
  docker_container:
    name: mongo
    image: papetua/mongo:v2.0.0
    state: started
    restart_policy: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
    networks:
      - name: app-net
  tags:
    - database
    - backend