---
- name: Create Docker network
  docker_network:
    name: "{{ docker_network }}"
    state: present

- name: Create MongoDB volume
  docker_volume:
    name: "{{ mongo_volume_name }}"
    state: present

- name: Run MongoDB Container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ mongo_port }}"
    volumes:
      - "{{ mongo_volume_path }}"
    networks:
      - name: "{{ docker_network }}"
  tags:
    - database
    - backend
  become: true
