---
- name: Clone application repository
  git:
    repo: "{{ repo_url }}"
    dest: /home/vagrant/app
    version: master

- name: Run backend container
  docker_container:
    name: yolo-backend
    image: papetua/yolo_backend:v2.0.0
    state: started
    restart_policy: always
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    command: "npm start"

    tags:
    - backend

  become: yes